I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 72, in script call
    call episode1
  File "game/episode 1.rpy", line 87, in script
    $ change_confidence(+2)
  File "game/episode 1.rpy", line 87, in <module>
    $ change_confidence(+2)
TypeError: change_confidence() missing 1 required positional argument: 'amount'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 72, in script call
    call episode1
  File "game/episode 1.rpy", line 87, in script
    $ change_confidence(+2)
  File "E:\monokums\004_Softwares\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\monokums\004_Softwares\Renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/episode 1.rpy", line 87, in <module>
    $ change_confidence(+2)
TypeError: change_confidence() missing 1 required positional argument: 'amount'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Capstone 1.0
Sat Oct 25 21:26:39 2025
